version: '3.5'
services:
  homeassistant:
    restart: unless-stopped
    image: ghcr.io/home-assistant/home-assistant:stable
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Rome
    volumes:
      - ../../docker/data/ha:/config
  
  ewpe:
    image: demydiuk/ewpe-smart-mqtt:1.0.5
    network_mode: host