version: "3.4"
include:
  - ./ha/docker-compose.yml

services:
  php:
    extends:
      file: ./gest-be/docker-compose.yml
      service: php
    build:
      context: ./gest-be
      args:
        SENTRY_DSN: ${SENTRY_DSN}
    image: fullbl/hora-be:${TAG:-latest}
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      LOCATION: ${LOCATION}
      SECOND_LEVEL_DOMAIN: ${SECOND_LEVEL_DOMAIN}
      HA_TOKEN: ${HA_TOKEN}
      SENTRY_DSN: ${SENTRY_DSN}
    restart: always

  database:
    extends:
      file: ./gest-be/docker-compose.yml
      service: database
    restart: always

  caddy:
    extends:
      file: ./gest-be/docker-compose.yml
      service: caddy
    build:
      context: ./gest-be
    environment:
      LOCATION: ${LOCATION}      
      SECOND_LEVEL_DOMAIN: ${SECOND_LEVEL_DOMAIN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  app:
    build: 
      context: ./gest-fe
      dockerfile: ../Dockerfile
      args:
        LOCATION: belluno
        SECOND_LEVEL_DOMAIN: horafarms.it
        SENTRY_DSN: ${SENTRY_DSN_FE}
    image: fullbl/hora-app:${TAG:-latest}
    restart: always

volumes:
  php_socket:
  caddy_data:
  caddy_config: